import '../../l10n/app_localizations.dart';

/// Maps the canonical English titles of seeded and library amal
/// (stored verbatim in the DB) to their localized display names.
///
/// The stored string doubles as the lookup key, so a title the user has
/// renamed no longer matches and falls through untouched — that's what keeps
/// this from clobbering their own wording. `isSeed` can't serve as the gate
/// here: it survives a rename, and library-created rows never set it.
String localizedAmalTitle(String dbTitle, AppLocalizations l) {
  return switch (dbTitle) {
    'Fajr' => l.amalFajr,
    'Dhuhr' => l.amalDhuhr,
    'Asr' => l.amalAsr,
    'Maghrib' => l.amalMaghrib,
    'Isha' => l.amalIsha,
    'Tahajjud' => l.amalTahajjud,
    'Duha' || 'Duha Prayer' => l.amalDuha,
    'Morning Adhkar' => l.amalMorningAdhkar,
    'Evening Adhkar' => l.amalEveningAdhkar,
    'Tilawah' => l.amalTilawah,
    'Surah Kahf' => l.amalSurahKahf,
    'Sadaqah' => l.amalSadaqah,
    'Tasbih 33x' => l.amalTasbih,
    'Istighfar' || 'Istighfar 100x' => l.amalIstighfar,
    'Five daily prayers' => l.amalFivePrayers,
    "Jumu'ah" => l.amalJumuah,
    'Witr' => l.amalWitr,
    'Qada prayers' => l.amalQada,
    'Fajr Sunnah' => l.amalFajrSunnah,
    'Dhuhr Sunnah' => l.amalDhuhrSunnah,
    'Asr Sunnah' => l.amalAsrSunnah,
    'Maghrib Sunnah' => l.amalMaghribSunnah,
    'Isha Sunnah' => l.amalIshaSunnah,
    'Sunnah Rawatib' => l.amalRawatib,
    'Siwak' => l.amalSiwak,
    'Wudu before sleep' => l.amalWuduSleep,
    'Friday ghusl' => l.amalFridayGhusl,
    'Ishraq' => l.amalIshraq,
    "Two rak'ahs after wudu" => l.amalWuduPrayer,
    'Tahiyyat al-Masjid' => l.amalTahiyyah,
    "Early to Jumu'ah" => l.amalEarlyJumuah,
    'After-Salah Adhkar' => l.amalAfterSalah,
    'After-Fajr Adhkar' => l.amalAfterFajr,
    'After-Dhuhr Adhkar' => l.amalAfterDhuhr,
    'After-Asr Adhkar' => l.amalAfterAsr,
    'After-Maghrib Adhkar' => l.amalAfterMaghrib,
    'After-Isha Adhkar' => l.amalAfterIsha,
    'Ayat al-Kursi' => l.amalAyatKursi,
    'Ayat al-Kursi after Fajr' => l.amalKursiFajr,
    'Ayat al-Kursi after Dhuhr' => l.amalKursiDhuhr,
    'Ayat al-Kursi after Asr' => l.amalKursiAsr,
    'Ayat al-Kursi after Maghrib' => l.amalKursiMaghrib,
    'Ayat al-Kursi after Isha' => l.amalKursiIsha,
    'Sayyid al-Istighfar' => l.amalSayyidIstighfar,
    'Salawat' => l.amalSalawat,
    'SubhanAllahi wa bihamdihi' => l.amalSubhanallah,
    'La ilaha illallah' => l.amalTahlil,
    'Bedtime Adhkar' => l.amalBedtimeAdhkar,
    'Friday Salawat' => l.amalFridaySalawat,
    'La hawla wa la quwwata' => l.amalHawqala,
    'Tasbih Fatimah' => l.amalTasbihFatimah,
    'Waking Adhkar' => l.amalWakingAdhkar,
    'Dua after Adhan' => l.amalDuaAdhan,
    'Dua between Adhan & Iqamah' => l.amalDuaIqamah,
    'Dua in Sujood' => l.amalDuaSujood,
    'Dua for parents' => l.amalDuaParents,
    'Dua for others' => l.amalDuaOthers,
    "Dua in Friday's last hour" => l.amalFridayHour,
    'Night dua (last third)' => l.amalLastThird,
    'Surah al-Mulk' => l.amalMulk,
    'Last 2 ayat of al-Baqarah' => l.amalBaqarahEnd,
    'Surah as-Sajdah' => l.amalSajdah,
    'Three Quls' => l.amalQuls,
    'Surah Yasin' => l.amalYasin,
    "Surah al-Waqi'ah" => l.amalWaqiah,
    'Hifz' => l.amalHifz,
    'Hifz revision' => l.amalMurajaah,
    'Tafsir' => l.amalTafsir,
    'Listen to Quran' => l.amalListenQuran,
    'Teach Quran' => l.amalTeachQuran,
    'Monday & Thursday fast' => l.amalMonThu,
    '3 fasts a month' => l.amalThreeDays,
    'Daily Sadaqah' => l.amalDailySadaqah,
    'Feed someone' => l.amalFeed,
    'Help someone in need' => l.amalHelpNeed,
    'Support an orphan' => l.amalOrphan,
    'Give water' => l.amalGiveWater,
    'Learn a hadith' => l.amalLearnHadith,
    'Read an Islamic book' => l.amalReadBook,
    'Study the Seerah' => l.amalSeerah,
    'Attend a class' => l.amalClass,
    'Learn Arabic' => l.amalArabic,
    'Learn a new dua' => l.amalLearnDua,
    'Share what you learn' => l.amalShare,
    'Study fiqh' => l.amalFiqh,
    'Nightly Muhasaba' => l.amalMuhasaba,
    'Speak good or stay silent' => l.amalSpeakGood,
    'No backbiting' => l.amalNoBackbiting,
    'Control anger' => l.amalAnger,
    'Lower the gaze' => l.amalGaze,
    'Be truthful' => l.amalTruthful,
    'Smile' => l.amalSmile,
    'Spread salam' => l.amalSalam,
    'Forgive others' => l.amalForgive,
    'Gratitude' => l.amalGratitude,
    'Visit the sick' => l.amalVisitSick,
    'Kindness to neighbours' => l.amalNeighbours,
    'Remove harm from the path' => l.amalRemoveHarm,
    'Kindness to parents' => l.amalParents,
    'Keep family ties' => l.amalFamilyTies,
    'Help at home' => l.amalHelpHome,
    'Teach your children' => l.amalTeachChildren,
    'Kindness to spouse' => l.amalSpouse,
    _ => dbTitle, // user-created or renamed titles stay as-is
  };
}
