// File generated by FlutterFire CLI, then hand-trimmed to iOS + Android only
// since this app intentionally does not support web or desktop targets.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Muhasaba only ships on iOS and Android. '
          'Target ${defaultTargetPlatform.name} is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9mGguacIdCUG7GBR6C4stKj0d6_iRYE',
    appId: '1:525146256049:android:21db500909a9f24ac76890',
    messagingSenderId: '525146256049',
    projectId: 'muhasaba-dev',
    storageBucket: 'muhasaba-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKrh2_AmvL75dhgR13dlKroMqh3sPonRQ',
    appId: '1:525146256049:ios:de86f11be8661db7c76890',
    messagingSenderId: '525146256049',
    projectId: 'muhasaba-dev',
    storageBucket: 'muhasaba-dev.firebasestorage.app',
    iosBundleId: 'dev.hadi.muhasaba',
  );
}
