// File generated by FlutterFire CLI, then hand-trimmed to iOS + Android only
// since this app intentionally does not support web or desktop targets.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Muhasaba only ships on iOS and Android. '
          'Target ${defaultTargetPlatform.name} is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMoXO41NYCAZnujxtRSkXGmRosrTzHTA',
    appId: '1:234302098015:android:c051ef9a5485fb2b9d29ea',
    messagingSenderId: '234302098015',
    projectId: 'mukashi-muhasaba',
    storageBucket: 'mukashi-muhasaba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIE5Sv4AOuP07fpFB3oxfZ-wDZeoDnVek',
    appId: '1:234302098015:ios:c37c918b01e8914b9d29ea',
    messagingSenderId: '234302098015',
    projectId: 'mukashi-muhasaba',
    storageBucket: 'mukashi-muhasaba.firebasestorage.app',
    iosBundleId: 'dev.mukashi.muhasaba',
  );

}